services:
  - type: web
    name: portal-link-command
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn server:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false  # Tämä tarkoittaa että lisäät sen käsin Renderin hallinnasta